language: java
java:
  oraclejdk8
branches:
  only:
    - master
install:
  mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  mvn clean install
after_script:
  mvn coveralls:report
